---
output:
  github_document:
    html_preview: false
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
options(tibble.print_min = 5, tibble.print_max = 5)
```

# ophion


## Overview


## Installation

To install from github:

```{r eval = FALSE}
library(devtools)
install_github(repo="bmeg/ophion", subdir="client/R")
```

To install locally:
```{bash eval = FALSE}
git clone https://github.com/bmeg/ophion.git
cd ophion/client/R
R CMD INSTALL .
```

## Usage
```{r eval = FALSE}
library(ophion)
library(magrittr)

# Preview a query
ophion("bmeg.io") %>%
    query() %>%
    has("gid", "cohort:TCGA-READ") %>%
    outgoing("hasSample") %>%
    incoming("expressionFor") %>%
    render()

# Execute a query
ophion("bmeg.io") %>% 
  query() %>%
  has("gid", within(c("CCLE:OCIM1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE", "biosample:CCLE:JHUEM2_ENDOMETRIUM"))) %>% 
  execute()
```
